### ISSUE TITLE
How to embed "image-list" in the record.twig - this not worked via Image-Slider in bolt 3.5.7

### ISSUE THREAD

**Issue by ghost** [nestordedios/bolt-theme-spatial#7]
Hi Developers,

how to embed `image-list` in the record.twig. In your Theme ist this not defined and not worked.

I wish a image slider under regular Bolt Image.

Can yor help me with this?

Thanks in Advance..

**Comment by nestordedios** [comment]
Hi @AlexL777 ,

As you already said, the imagelist field is not defined in `record.twig`. You need to add it.

You can add it like this: 
```
{% if record.nameOfImageListField is not empty %}
    {% for image in record.nameOfImageListField %}
        {{ image|thumbnail() }}
    {% endfor %}
{% endif %}
```

Feel free to open a Pull Request for it.

**Comment by ghost** [comment]
Hi,
thanks for your Reply. this not worked with me under https://shop.boltcmsservice.de/produkt/webseitenerstellung-in-bolt-cms-ab-500-eur# . Ich have this in the contenttypes.yml.

    imagelist:
            type: imagelist
            postfix: "<p><em>Additional images for the project.</em></p>"
            extensions: [ gif, jpg, png ]

**Comment by nestordedios** [comment]
Are you using the name of your image list field?

From my snippet `record.nameOfImageListField` has to become `record.imagelist` in your case.

If you need further help you can always ask on the Slack channel.

**Comment by ghost** [comment]
I have this now so. Under https://shop.boltcmsservice.de/produkt/bolt-service-domain-hosterumzug-mit-bolt-webseite i see only thumb-url and no image-list.

Can you help me with this?

**Comment by ghost** [comment]
I have posted my Problem in Slack.

**Comment by nestordedios** [comment]
@AlexL777 I'm closing this issue. It has been solved in the general channel.
